---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-config
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore-sm
    kind: ClusterSecretStore
  target:
    name: backstage-config
  data:
    - secretKey: BACKSTAGE_URL
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/backstage-url
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: abc/abc:abc
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef: backstage-config
