---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-config
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore-sm
    kind: ClusterSecretStore
  target:
    name: backstage-config
  data:
    - secretKey: BACKSTAGE_FRONTEND_URL
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/backstage-url
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/postgres-endpoint
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/postgres-port
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/postgres-password
    - secretKey: KEYCLOAK_NAME_METADATA
      remoteRef:
        key: https://keycloak.development.idp.beg-dev.io/realms/cnoe/.well-known/openid-configuration

  # ARGO_WORKFLOWS_URL: https://${ARGO_WORKFLOWS_DOMAIN_NAME}
  KEYCLOAK_NAME_METADATA: https://${KEYCLOAK_DOMAIN_NAME}/realms/cnoe/.well-known/openid-configuration
  KEYCLOAK_CLIENT_SECRET: "${CLIENT_SECRET}"
  ARGOCD_AUTH_TOKEN: "argocd.token=${argocdToken}"
  ARGO_CD_URL: "http://argocd-server.argocd.svc.cluster.local/api/v1/"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: "ghcr.io/cnoe-io/backstage-app:135c0cb26f3e004a27a11edb6a4779035aff9805"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - name: http
              containerPort: 7007
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: backstage
  type: ClusterIP
