apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  namespace: keycloak
  labels:
    app: postgresql
spec:
  storageClassName: gp2
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: keycloak
  labels:
    app: postgresql
spec:
  serviceName: service-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 300Mi
          image: docker.io/library/postgres:15.3-alpine3.18
          envFrom:
            - secretRef:
                name: postgresql-config
          ports:
            - containerPort: 5432
              name: postgresdb
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgress
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgresql

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: keycloak
  labels:
    app: postgresql
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:22.0.0
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
