---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-config
  namespace: keycloak
spec:
  refreshInterval: 3m
  secretStoreRef:
    name: cluster-secretstore-sm
    kind: ClusterSecretStore
  target:
    name: keycloak-config
  data:
    - secretKey: KC_HOSTNAME
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/keycloak-url
    - secretKey: KC_DB_URL_HOST
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/postgres-endpoint
    - secretKey: KC_DB_URL_PORT
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/postgres-port
    - secretKey: KC_DB_URL_DATABASE
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/postgres-database-name
    - secretKey: KC_DB_USERNAME
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/postgres-user
    - secretKey: KC_DB_PASSWORD
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/postgres-password
    - secretKey: KC_BOOTSTRAP_ADMIN_USERNAME
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/keycloak-user
    - secretKey: KC_BOOTSTRAP_ADMIN_PASSWORD
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/keycloak-password
# ---
# apiVersion: k8s.keycloak.org/v2alpha1
# kind: Keycloak
# metadata:
#   labels:
#     app: keycloak
#   name: keycloak
#   namespace: keycloak
# spec:
#   resources:
#     requests:
#       cpu: "1"
#       memory: 512M"
#     limits:
#       cpu: "4"
#       memory: "2250M"
#   image: camunda/keycloak:26
#   startOptimized: false
#   # envFrom:
#   #   - secretRef:
#   #       name: keycloak-config
#   instances: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: camunda/keycloak:26
          args: ["start-dev"]
          env:
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_FEATURES
              value: "hostname:v2"
            # - name: PROXY_ADDRESS_FORWARDING
            #   value: "true"
            # - name: KC_HOSTNAME_STRICT
            #   value: "false"
            # - name: HOSTNAME_STRICT
            #   value: "false"
            # - name: KC_HOSTNAME_STRICT
            #   value: "false"
            # - name: KC_HTTP_ENABLED
            #   value: "true"
            # - name: KC_PROXY
            #   value: "edge"
            # - name: KC_PROXY_ADDRESS_FORWARDING
            #   value: "true"
            # - name: KC_HOSTNAME_STRICT_HTTPS
            #   value: "false"
          envFrom:
            - secretRef:
                name: keycloak-config
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
