apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-config
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore-sm
    kind: ClusterSecretStore
  target:
    name: keycloak-config
  data:
    - secretKey: URL
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/keycloak-url
    - secretKey: KEYCLOAK_USER
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/keycloak-user
    - secretKey: KEYCLOACK_PASSWORD
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/keycloak-password
    - secretKey: POSTGRES_URL
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/postgres-endpoint
    - secretKey: POSTGRES_READER_URL
      remoteRef:
        key: /ebbo/idp/ebbo/f70b0f0/postgres-reader-endpoint

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1
          args: ["start-dev"]
          envFrom:
            - secretRef:
                name: keycloak-config
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
---

