apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    external-dns.alpha.kubernetes.io/hostname: argocd.development.idp.beg-dev.io

  name: {{ template "helm-guestbook.fullname" . }}
spec:
  rules:
  - host: argocd.development.idp.beg-dev.io
    http:
      paths:
      - path: /
        backend:
          service:
            name: {{ template "helm-guestbook.fullname" . }}
            port:
              number: 80
        pathType: Prefix